// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/event/proto/event.proto

package event

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Result struct {
	State                int64    `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_62c5e32b2ac3b5ad, []int{0}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetState() int64 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// message
type Request struct {
	// unique id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// unix timestamp
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// message
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_62c5e32b2ac3b5ad, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Request) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Result)(nil), "Result")
	proto.RegisterType((*Request)(nil), "Request")
}

func init() { proto.RegisterFile("srv/event/proto/event.proto", fileDescriptor_62c5e32b2ac3b5ad) }

var fileDescriptor_62c5e32b2ac3b5ad = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0x41, 0x0e, 0x82, 0x30,
	0x10, 0x45, 0x85, 0x06, 0xb0, 0xb3, 0x30, 0xa6, 0x71, 0xd1, 0xa8, 0x0b, 0xc2, 0x0a, 0x37, 0x60,
	0xf4, 0x0c, 0x1e, 0xc0, 0x7a, 0x02, 0x0c, 0x13, 0x42, 0x62, 0x01, 0x99, 0x81, 0xf3, 0x1b, 0x5a,
	0x8d, 0xbb, 0xf7, 0x9a, 0xfe, 0xcc, 0x83, 0x03, 0x8d, 0x73, 0x89, 0x33, 0x76, 0x5c, 0x0e, 0x63,
	0xcf, 0xbd, 0xe7, 0xc2, 0x71, 0x76, 0x86, 0xd8, 0x20, 0x4d, 0x2f, 0x56, 0x3b, 0x88, 0x88, 0x2b,
	0x46, 0x1d, 0xa4, 0x41, 0x2e, 0x8c, 0x17, 0xb5, 0x05, 0x61, 0xa9, 0xd1, 0x61, 0x1a, 0xe4, 0xd2,
	0x2c, 0x98, 0xdd, 0x21, 0x31, 0xf8, 0x9e, 0x90, 0x58, 0x6d, 0x20, 0x6c, 0x6b, 0xf7, 0x5f, 0x9a,
	0xb0, 0xad, 0xd5, 0x11, 0x24, 0xb7, 0x16, 0x89, 0x2b, 0x3b, 0xb8, 0x89, 0x30, 0xff, 0x07, 0xa5,
	0x21, 0xb1, 0x48, 0x54, 0x35, 0xa8, 0x85, 0x9b, 0xfc, 0xf4, 0x72, 0x82, 0xe8, 0xb6, 0x34, 0xa9,
	0x14, 0xe4, 0x03, 0xbb, 0xda, 0xcb, 0xba, 0xf8, 0xde, 0xd9, 0x27, 0x85, 0x6f, 0xcc, 0x56, 0xcf,
	0xd8, 0x65, 0x5f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x13, 0x7f, 0x82, 0xd5, 0x00, 0x00,
	0x00,
}
