// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/email/proto/email.proto

package email

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Example message
type Email struct {
	// unique id
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// unix timestamp
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// message
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d7966dc7e725bb0, []int{0}
}

func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (m *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(m, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Email) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Email) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Email)(nil), "Email")
}

func init() { proto.RegisterFile("srv/email/proto/email.proto", fileDescriptor_5d7966dc7e725bb0) }

var fileDescriptor_5d7966dc7e725bb0 = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x2e, 0x2a, 0xd3,
	0x4f, 0xcd, 0x4d, 0xcc, 0xcc, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x87, 0xb0, 0xf5, 0xc0, 0x6c,
	0x25, 0x77, 0x2e, 0x56, 0x57, 0x10, 0x57, 0x88, 0x8f, 0x8b, 0xa9, 0x24, 0x5f, 0x82, 0x51, 0x81,
	0x51, 0x83, 0x33, 0x88, 0xa9, 0x24, 0x5f, 0x48, 0x84, 0x8b, 0xb5, 0x24, 0xb3, 0x24, 0x27, 0x55,
	0x82, 0x09, 0x2c, 0x04, 0xe1, 0x08, 0x49, 0x70, 0xb1, 0xe7, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7,
	0x4a, 0x30, 0x83, 0xc5, 0x61, 0xdc, 0x24, 0x36, 0xb0, 0x79, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa3, 0x81, 0x3f, 0xe7, 0x6e, 0x00, 0x00, 0x00,
}
