// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/auth/proto/auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71a9cb9a112a8986, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *LoginRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type LoginResult struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResult) Reset()         { *m = LoginResult{} }
func (m *LoginResult) String() string { return proto.CompactTextString(m) }
func (*LoginResult) ProtoMessage()    {}
func (*LoginResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_71a9cb9a112a8986, []int{1}
}

func (m *LoginResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResult.Unmarshal(m, b)
}
func (m *LoginResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResult.Marshal(b, m, deterministic)
}
func (m *LoginResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResult.Merge(m, src)
}
func (m *LoginResult) XXX_Size() int {
	return xxx_messageInfo_LoginResult.Size(m)
}
func (m *LoginResult) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResult.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResult proto.InternalMessageInfo

func (m *LoginResult) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Request struct {
	AuthToken            string   `protobuf:"bytes,1,opt,name=authToken,proto3" json:"authToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_71a9cb9a112a8986, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

type Result struct {
	State                int64    `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_71a9cb9a112a8986, []int{3}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetState() int64 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "auth.LoginRequest")
	proto.RegisterType((*LoginResult)(nil), "auth.LoginResult")
	proto.RegisterType((*Request)(nil), "auth.Request")
	proto.RegisterType((*Result)(nil), "auth.Result")
}

func init() { proto.RegisterFile("srv/auth/proto/auth.proto", fileDescriptor_71a9cb9a112a8986) }

var fileDescriptor_71a9cb9a112a8986 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0x4d, 0x4f, 0x84, 0x30,
	0x10, 0x75, 0x5d, 0x76, 0x0d, 0x03, 0x26, 0x3a, 0xf1, 0x80, 0xc6, 0x83, 0xa9, 0x07, 0x3d, 0x18,
	0x20, 0xea, 0x1f, 0xf0, 0xee, 0x89, 0x18, 0xef, 0x18, 0xcb, 0x47, 0x14, 0x8a, 0xed, 0x54, 0xe3,
	0xbf, 0x37, 0x9d, 0xd2, 0x80, 0xb7, 0xf7, 0x5e, 0xde, 0x47, 0xa7, 0x70, 0x6e, 0xf4, 0x77, 0x51,
	0x5b, 0xea, 0x8a, 0x49, 0x2b, 0x52, 0x0c, 0x73, 0x86, 0x18, 0x39, 0x2c, 0x1e, 0x21, 0x7d, 0x56,
	0x6d, 0x3f, 0x56, 0xf2, 0xcb, 0x4a, 0x43, 0x88, 0x10, 0x59, 0x23, 0x75, 0xb6, 0xb9, 0xda, 0xdc,
	0xc6, 0x15, 0x63, 0x3c, 0x81, 0xed, 0xf4, 0xf3, 0x9e, 0x1d, 0xb2, 0xe4, 0xa0, 0xb8, 0x86, 0x64,
	0x4e, 0x19, 0xfb, 0x49, 0x78, 0x06, 0x3b, 0x52, 0x1f, 0x72, 0x9c, 0x53, 0x9e, 0x88, 0x1b, 0x38,
	0x0a, 0xad, 0x97, 0x10, 0xbb, 0xb5, 0x97, 0x95, 0x69, 0x11, 0x44, 0x09, 0xfb, 0xa5, 0xc8, 0x50,
	0x4d, 0x92, 0x3d, 0xdb, 0xca, 0x13, 0xb7, 0x3f, 0x98, 0x36, 0xec, 0x0f, 0xa6, 0xbd, 0x6f, 0x20,
	0x7a, 0xb2, 0xd4, 0x61, 0x09, 0x3b, 0x7e, 0x07, 0x62, 0xce, 0x97, 0xad, 0x4f, 0xb9, 0x38, 0xfd,
	0xa7, 0xb9, 0x7e, 0x71, 0x80, 0x77, 0x90, 0xbc, 0x4a, 0xdd, 0x37, 0xbf, 0x3c, 0x8d, 0xc7, 0xde,
	0x13, 0x22, 0x69, 0xa0, 0xde, 0xfd, 0xb6, 0xe7, 0xaf, 0x7a, 0xf8, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0xbb, 0xe9, 0xef, 0xdd, 0x47, 0x01, 0x00, 0x00,
}
